PUT http://localhost:8080/user?id=8c512d42-7ef6-4839-86f3-997836556df6
Content-Type: application/json

{
  "newIncomeValue": 100000.01,
  "actor": "tax reporter",
  "reason": "Increased balance established"
}
