PUT http://localhost:8080/user?id=5bd236c4-1f74-4969-a17e-6cc29220762f
Content-Type: application/json

{
  "newIncomeValue": 100000.01,
  "actor": "tax reporter",
  "reason": "Increased balance established"
}
